server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: registry-service
    prefer-ip-address: true